CREATE TABLE ingest_checkpoint (
  checkpoint_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entity_kind VARCHAR(32) NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  last_raw_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  processed_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ingest_checkpoint (entity_kind, batch_id)
) ENGINE=InnoDB;
