CREATE TABLE chat_session_state (
  chat_session_state_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(64) NULL,
  tenant_id VARCHAR(64) NULL,
  state_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  last_turn_id VARCHAR(64) NULL,
  last_idempotency_key VARCHAR(96) NULL,
  fallback_count INT UNSIGNED NOT NULL DEFAULT 0,
  unresolved_context_json JSON NULL,
  pending_action_json JSON NULL,
  selection_json JSON NULL,
  summary_short VARCHAR(1000) NULL,
  last_trace_id VARCHAR(64) NULL,
  last_request_id VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  UNIQUE KEY uq_chat_session_state_conversation (conversation_id),
  INDEX idx_chat_session_state_user (user_id),
  INDEX idx_chat_session_state_updated (updated_at),
  INDEX idx_chat_session_state_expires (expires_at)
) ENGINE=InnoDB;

CREATE TABLE chat_turn_event (
  chat_turn_event_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id VARCHAR(128) NOT NULL,
  turn_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  route VARCHAR(32) NULL,
  reason_code VARCHAR(64) NULL,
  trace_id VARCHAR(64) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  payload_json JSON NULL,
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_chat_turn_event (conversation_id, turn_id, event_type),
  INDEX idx_chat_turn_event_conversation_time (conversation_id, event_time),
  INDEX idx_chat_turn_event_trace_time (trace_id, event_time),
  INDEX idx_chat_turn_event_request_time (request_id, event_time)
) ENGINE=InnoDB;

CREATE TABLE chat_action_audit (
  chat_action_audit_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  conversation_id VARCHAR(128) NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  action_state VARCHAR(32) NOT NULL DEFAULT 'RECORDED',
  decision VARCHAR(32) NOT NULL DEFAULT 'ALLOW',
  result VARCHAR(32) NOT NULL DEFAULT 'RECORDED',
  actor_user_id VARCHAR(64) NULL,
  actor_admin_id VARCHAR(64) NULL,
  target_ref VARCHAR(128) NULL,
  auth_context_json JSON NULL,
  trace_id VARCHAR(64) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  reason_code VARCHAR(64) NULL,
  idempotency_key VARCHAR(96) NULL,
  metadata_json JSON NULL,
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_chat_action_audit_idempotency (idempotency_key),
  INDEX idx_chat_action_audit_conversation_time (conversation_id, event_time),
  INDEX idx_chat_action_audit_actor_time (actor_user_id, event_time),
  INDEX idx_chat_action_audit_trace_time (trace_id, event_time),
  INDEX idx_chat_action_audit_request_time (request_id, event_time)
) ENGINE=InnoDB;
